server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TORNEO
    username: postgres
    password: Marcobustos9
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
